name: noto_3d_emoji
description: Google Noto 3D Emoji for Flutter. Downloads and caches the latest Noto Color Emoji font from a custom server.
version: 1.0.0
repository: https://github.com/IILLUMINATION/noto_3d_emoji
homepage: https://github.com/IILLUMINATION/noto_3d_emoji

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - emoji
  - font
  - noto
